app.cli.enabled=true
server.address=127.0.0.1
server.port=0

# Usa o mesmo banco persistente configurado em application.properties.
spring.h2.console.enabled=false

spring.main.banner-mode=off
logging.config=classpath:logback-terminal.xml
logging.file.name=./data/matricula-mais.log
spring.devtools.restart.enabled=false
